DROP TABLE IF EXISTS short_adjective;
DROP TABLE IF EXISTS long_adjective;
DROP TABLE IF EXISTS noun;

BEGIN;

CREATE TABLE short_adjective (id serial PRIMARY KEY, string varchar);
CREATE TABLE long_adjective (id serial PRIMARY KEY, string varchar);
CREATE TABLE noun (id serial PRIMARY KEY, string varchar);

/*INSERT INTO short_adjective (string) VALUES ('artless');
INSERT INTO short_adjective (string) VALUES ('bawdy');
INSERT INTO short_adjective (string) VALUES ('beslubbering');
INSERT INTO short_adjective (string) VALUES ('bootless');
INSERT INTO short_adjective (string) VALUES ('churlish');
INSERT INTO short_adjective (string) VALUES ('cockered');
INSERT INTO short_adjective (string) VALUES ('clouted');
INSERT INTO short_adjective (string) VALUES ('craven');
INSERT INTO short_adjective (string) VALUES ('currish');
INSERT INTO short_adjective (string) VALUES ('dankish');
INSERT INTO short_adjective (string) VALUES ('dissembling');
INSERT INTO short_adjective (string) VALUES ('droning');
INSERT INTO short_adjective (string) VALUES ('errant');
INSERT INTO short_adjective (string) VALUES ('fawning');
INSERT INTO short_adjective (string) VALUES ('fobbing');
INSERT INTO short_adjective (string) VALUES ('froward');
INSERT INTO short_adjective (string) VALUES ('frothy');
INSERT INTO short_adjective (string) VALUES ('gleeking');
INSERT INTO short_adjective (string) VALUES ('goatish');
INSERT INTO short_adjective (string) VALUES ('gorbellied');
INSERT INTO short_adjective (string) VALUES ('impertinent');
INSERT INTO short_adjective (string) VALUES ('infectious');
INSERT INTO short_adjective (string) VALUES ('jarring');
INSERT INTO short_adjective (string) VALUES ('loggerheaded');
INSERT INTO short_adjective (string) VALUES ('lumpish');
INSERT INTO short_adjective (string) VALUES ('mammering');
INSERT INTO short_adjective (string) VALUES ('mangled');
INSERT INTO short_adjective (string) VALUES ('mewling');
INSERT INTO short_adjective (string) VALUES ('paunchy');
INSERT INTO short_adjective (string) VALUES ('pribbling');
INSERT INTO short_adjective (string) VALUES ('puking');
INSERT INTO short_adjective (string) VALUES ('puny');
INSERT INTO short_adjective (string) VALUES ('qualling');
INSERT INTO short_adjective (string) VALUES ('rank');
INSERT INTO short_adjective (string) VALUES ('reeky');
INSERT INTO short_adjective (string) VALUES ('roguish');
INSERT INTO short_adjective (string) VALUES ('ruttish');
INSERT INTO short_adjective (string) VALUES ('saucy');
INSERT INTO short_adjective (string) VALUES ('spleeny');
INSERT INTO short_adjective (string) VALUES ('spongy');
INSERT INTO short_adjective (string) VALUES ('surly');
INSERT INTO short_adjective (string) VALUES ('tottering');
INSERT INTO short_adjective (string) VALUES ('unmuzzled');
INSERT INTO short_adjective (string) VALUES ('vain');
INSERT INTO short_adjective (string) VALUES ('venomed');
INSERT INTO short_adjective (string) VALUES ('villainous');
INSERT INTO short_adjective (string) VALUES ('warped');
INSERT INTO short_adjective (string) VALUES ('wayward');
INSERT INTO short_adjective (string) VALUES ('weedy');
INSERT INTO short_adjective (string) VALUES ('yeasty');*/


INSERT INTO short_adjective (string) VALUES ('artless');
INSERT INTO short_adjective (string) VALUES ('bawdy');
INSERT INTO short_adjective (string) VALUES ('beslubbering');
INSERT INTO short_adjective (string) VALUES ('без загрузки');
INSERT INTO short_adjective (string) VALUES ('churlish');
INSERT INTO short_adjective (string) VALUES ('cockered');
INSERT INTO short_adjective (string) VALUES ('clouted');
INSERT INTO short_adjective (string) VALUES ('craven');
INSERT INTO short_adjective (string) VALUES ('currish');
INSERT INTO short_adjective (string) VALUES ('dankish');
INSERT INTO short_adjective (string) VALUES ('разоблачение');
INSERT INTO short_adjective (string) VALUES ('гудение');
INSERT INTO short_adjective (string) VALUES ('errant');
INSERT INTO short_adjective (string) VALUES ('fawning');
INSERT INTO short_adjective (string) VALUES ('fobbing');
INSERT INTO short_adjective (string) VALUES ('froward');
INSERT INTO short_adjective (string) VALUES ('frothy');
INSERT INTO short_adjective (string) VALUES ('gleeking');
INSERT INTO short_adjective (string) VALUES ('козий');
INSERT INTO short_adjective (string) VALUES ('gorbellied');
INSERT INTO short_adjective (string) VALUES ('наглый');
INSERT INTO short_adjective (string) VALUES ('инфекционный');
INSERT INTO short_adjective (string) VALUES ('jarring');
INSERT INTO short_adjective (string) VALUES ('loggerheaded');
INSERT INTO short_adjective (string) VALUES ('lumpish');
INSERT INTO short_adjective (string) VALUES ('mamering');
INSERT INTO short_adjective (string) VALUES ('искалеченный');
INSERT INTO short_adjective (string) VALUES ('мяуканье');
INSERT INTO short_adjective (string) VALUES ('paunchy');
INSERT INTO short_adjective (string) VALUES ('pribbling');
INSERT INTO short_adjective (string) VALUES ('puking');
INSERT INTO short_adjective (string) VALUES ('маленькое');
INSERT INTO short_adjective (string) VALUES ('qualling');
INSERT INTO short_adjective (string) VALUES ('rank');
INSERT INTO short_adjective (string) VALUES ('reeky');
INSERT INTO short_adjective (string) VALUES ('roguish');
INSERT INTO short_adjective (string) VALUES ('ruttish');
INSERT INTO short_adjective (string) VALUES ('saucy');
INSERT INTO short_adjective (string) VALUES ('spleeny');
INSERT INTO short_adjective (string) VALUES ('губчатый');
INSERT INTO short_adjective (string) VALUES ('неприветливый');
INSERT INTO short_adjective (string) VALUES ('колебание');
INSERT INTO short_adjective (string) VALUES ('unmuzzled');
INSERT INTO short_adjective (string) VALUES ('vain');
INSERT INTO short_adjective (string) VALUES ('venomed');
INSERT INTO short_adjective (string) VALUES ('злодейский');
INSERT INTO short_adjective (string) VALUES ('деформированный');
INSERT INTO short_adjective (string) VALUES ('своенравный');
INSERT INTO short_adjective (string) VALUES ('weedy');


/*INSERT INTO long_adjective (string) VALUES ('base-court');
INSERT INTO long_adjective (string) VALUES ('bat-fowling');
INSERT INTO long_adjective (string) VALUES ('beef-witted');
INSERT INTO long_adjective (string) VALUES ('beetle-headed');
INSERT INTO long_adjective (string) VALUES ('boil-brained');
INSERT INTO long_adjective (string) VALUES ('clapper-clawed');
INSERT INTO long_adjective (string) VALUES ('clay-brained');
INSERT INTO long_adjective (string) VALUES ('common-kissing');
INSERT INTO long_adjective (string) VALUES ('crook-pated');
INSERT INTO long_adjective (string) VALUES ('dismal-dreaming');
INSERT INTO long_adjective (string) VALUES ('dizzy-eyed');
INSERT INTO long_adjective (string) VALUES ('doghearted');
INSERT INTO long_adjective (string) VALUES ('dread-bolted');
INSERT INTO long_adjective (string) VALUES ('earth-vexing');
INSERT INTO long_adjective (string) VALUES ('elf-skinned');
INSERT INTO long_adjective (string) VALUES ('fat-kidneyed');
INSERT INTO long_adjective (string) VALUES ('fen-sucked');
INSERT INTO long_adjective (string) VALUES ('flap-mouthed');
INSERT INTO long_adjective (string) VALUES ('fly-bitten');
INSERT INTO long_adjective (string) VALUES ('folly-fallen');
INSERT INTO long_adjective (string) VALUES ('fool-born');
INSERT INTO long_adjective (string) VALUES ('full-gorged');
INSERT INTO long_adjective (string) VALUES ('guts-griping');
INSERT INTO long_adjective (string) VALUES ('half-faced');
INSERT INTO long_adjective (string) VALUES ('hasty-witted');
INSERT INTO long_adjective (string) VALUES ('hedge-born');
INSERT INTO long_adjective (string) VALUES ('hell-hated');
INSERT INTO long_adjective (string) VALUES ('idle-headed');
INSERT INTO long_adjective (string) VALUES ('ill-breeding');
INSERT INTO long_adjective (string) VALUES ('ill-nurtured');
INSERT INTO long_adjective (string) VALUES ('knotty-pated');
INSERT INTO long_adjective (string) VALUES ('milk-livered');
INSERT INTO long_adjective (string) VALUES ('motley-minded');
INSERT INTO long_adjective (string) VALUES ('onion-eyed');
INSERT INTO long_adjective (string) VALUES ('plume-plucked');
INSERT INTO long_adjective (string) VALUES ('pottle-deep');
INSERT INTO long_adjective (string) VALUES ('pox-marked');
INSERT INTO long_adjective (string) VALUES ('reeling-ripe');
INSERT INTO long_adjective (string) VALUES ('rough-hewn');
INSERT INTO long_adjective (string) VALUES ('rude-growing');
INSERT INTO long_adjective (string) VALUES ('rump-fed');
INSERT INTO long_adjective (string) VALUES ('shard-borne');
INSERT INTO long_adjective (string) VALUES ('sheep-biting');
INSERT INTO long_adjective (string) VALUES ('spur-galled');
INSERT INTO long_adjective (string) VALUES ('swag-bellied');
INSERT INTO long_adjective (string) VALUES ('tardy-gaited');
INSERT INTO long_adjective (string) VALUES ('tickle-brained');
INSERT INTO long_adjective (string) VALUES ('toad-spotted');
INSERT INTO long_adjective (string) VALUES ('unchin-snouted');
INSERT INTO long_adjective (string) VALUES ('weather-bitten');*/


INSERT INTO long_adjective (string) VALUES ('базовый корт');
INSERT INTO long_adjective (string) VALUES ('летучая мышь');
INSERT INTO long_adjective (string) VALUES ('умный');
INSERT INTO long_adjective (string) VALUES ('голова жука');
INSERT INTO long_adjective (string) VALUES ('boil-brained');
INSERT INTO long_adjective (string) VALUES ('clapper-clawed');
INSERT INTO long_adjective (string) VALUES ('глиняный мозг');
INSERT INTO long_adjective (string) VALUES ('общие поцелуи');
INSERT INTO long_adjective (string) VALUES ('криво');
INSERT INTO long_adjective (string) VALUES ('мрачные сны');
INSERT INTO long_adjective (string) VALUES ('головокружение');
INSERT INTO long_adjective (string) VALUES ('doghearted');
INSERT INTO long_adjective (string) VALUES ('dread-bolted');
INSERT INTO long_adjective (string) VALUES ('землетрясение');
INSERT INTO long_adjective (string) VALUES ('эльфийская кожа');
INSERT INTO long_adjective (string) VALUES ('толстая почка');
INSERT INTO long_adjective (string) VALUES ('fen-sucked');
INSERT INTO long_adjective (string) VALUES ('откидной створки');
INSERT INTO long_adjective (string) VALUES ('кусать муху');
INSERT INTO long_adjective (string) VALUES ('безумие падший');
INSERT INTO long_adjective (string) VALUES ('одураченный');
INSERT INTO long_adjective (string) VALUES ('full-gorged');
INSERT INTO long_adjective (string) VALUES ('guts-griping');
INSERT INTO long_adjective (string) VALUES ('половина лица');
INSERT INTO long_adjective (string) VALUES ('поспешный');
INSERT INTO long_adjective (string) VALUES ('рожденный хедж');
INSERT INTO long_adjective (string) VALUES ('адская ненависть');
INSERT INTO long_adjective (string) VALUES ('бездействующий');
INSERT INTO long_adjective (string) VALUES ('плохо размножающийся');
INSERT INTO long_adjective (string) VALUES ('плохо воспитанный');
INSERT INTO long_adjective (string) VALUES ('запутанный');
INSERT INTO long_adjective (string) VALUES ('живое молоко');
INSERT INTO long_adjective (string) VALUES ('разноцветные');
INSERT INTO long_adjective (string) VALUES ('ony-eyed');
INSERT INTO long_adjective (string) VALUES ('plume-plucked');
INSERT INTO long_adjective (string) VALUES ('pottle-deep');
INSERT INTO long_adjective (string) VALUES ('отмеченный оспой');
INSERT INTO long_adjective (string) VALUES ('созревший');
INSERT INTO long_adjective (string) VALUES ('грубо высечено');
INSERT INTO long_adjective (string) VALUES ('грубый рост');
INSERT INTO long_adjective (string) VALUES ('rump-feed');
INSERT INTO long_adjective (string) VALUES ('осколок');
INSERT INTO long_adjective (string) VALUES ('кусание овец');
INSERT INTO long_adjective (string) VALUES ('spur-galled');
INSERT INTO long_adjective (string) VALUES ('пижоник');
INSERT INTO long_adjective (string) VALUES ('tardy-gaited');
INSERT INTO long_adjective (string) VALUES ('tickle-brained');
INSERT INTO long_adjective (string) VALUES ('toad-spotted');
INSERT INTO long_adjective (string) VALUES ('unchin-snouted');
INSERT INTO long_adjective (string) VALUES ('укушенный погодой');


/*INSERT INTO noun (string) VALUES ('apple-john');
INSERT INTO noun (string) VALUES ('baggage');
INSERT INTO noun (string) VALUES ('barnacle');
INSERT INTO noun (string) VALUES ('bladder');
INSERT INTO noun (string) VALUES ('boar-pig');
INSERT INTO noun (string) VALUES ('bugbear');
INSERT INTO noun (string) VALUES ('bum-bailey');
INSERT INTO noun (string) VALUES ('canker-blossom');
INSERT INTO noun (string) VALUES ('clack-dish');
INSERT INTO noun (string) VALUES ('clotpole');
INSERT INTO noun (string) VALUES ('coxcomb');
INSERT INTO noun (string) VALUES ('codpiece');
INSERT INTO noun (string) VALUES ('death-token');
INSERT INTO noun (string) VALUES ('dewberry');
INSERT INTO noun (string) VALUES ('flap-dragon');
INSERT INTO noun (string) VALUES ('flax-wench');
INSERT INTO noun (string) VALUES ('flirt-gill');
INSERT INTO noun (string) VALUES ('foot-licker');
INSERT INTO noun (string) VALUES ('fustilarian');
INSERT INTO noun (string) VALUES ('giglet');
INSERT INTO noun (string) VALUES ('gudgeon');
INSERT INTO noun (string) VALUES ('haggard');
INSERT INTO noun (string) VALUES ('harpy');
INSERT INTO noun (string) VALUES ('hedge-pig');
INSERT INTO noun (string) VALUES ('horn-beast');
INSERT INTO noun (string) VALUES ('hugger-mugger');
INSERT INTO noun (string) VALUES ('joithead');
INSERT INTO noun (string) VALUES ('lewdster');
INSERT INTO noun (string) VALUES ('lout');
INSERT INTO noun (string) VALUES ('maggot-pie');
INSERT INTO noun (string) VALUES ('malt-worm');
INSERT INTO noun (string) VALUES ('mammet');
INSERT INTO noun (string) VALUES ('measle');
INSERT INTO noun (string) VALUES ('minnow');
INSERT INTO noun (string) VALUES ('miscreant');
INSERT INTO noun (string) VALUES ('moldwarp');
INSERT INTO noun (string) VALUES ('mumble-news');
INSERT INTO noun (string) VALUES ('nut-hook');
INSERT INTO noun (string) VALUES ('pigeon-egg');
INSERT INTO noun (string) VALUES ('pignut');
INSERT INTO noun (string) VALUES ('puttock');
INSERT INTO noun (string) VALUES ('pumpion');
INSERT INTO noun (string) VALUES ('ratsbane');
INSERT INTO noun (string) VALUES ('scut');
INSERT INTO noun (string) VALUES ('skainsmate');
INSERT INTO noun (string) VALUES ('strumpet');
INSERT INTO noun (string) VALUES ('varlot');
INSERT INTO noun (string) VALUES ('vassal');
INSERT INTO noun (string) VALUES ('whey-face');
INSERT INTO noun (string) VALUES ('wagtail');*/


INSERT INTO noun (string) VALUES ('apple-john');
INSERT INTO noun (string) VALUES ('багаж');
INSERT INTO noun (string) VALUES ('ракушка');
INSERT INTO noun (string) VALUES ('мочевой пузырь');
INSERT INTO noun (string) VALUES ('кабан свинья');
INSERT INTO noun (string) VALUES ('bugbear');
INSERT INTO noun (string) VALUES ('bum-bailey');
INSERT INTO noun (string) VALUES ('canker-blossom');
INSERT INTO noun (string) VALUES ('clack-dish');
INSERT INTO noun (string) VALUES ('clotpole');
INSERT INTO noun (string) VALUES ('coxcomb');
INSERT INTO noun (string) VALUES ('codpiece');
INSERT INTO noun (string) VALUES ('жетон смерти');
INSERT INTO noun (string) VALUES ('dewberry');
INSERT INTO noun (string) VALUES ('flap-dragon');
INSERT INTO noun (string) VALUES ('льняная девка');
INSERT INTO noun (string) VALUES ('flirt-gill');
INSERT INTO noun (string) VALUES ('foot-licker');
INSERT INTO noun (string) VALUES ('fustilarian');
INSERT INTO noun (string) VALUES ('giglet');
INSERT INTO noun (string) VALUES ('пескарь');
INSERT INTO noun (string) VALUES ('haggard');
INSERT INTO noun (string) VALUES ('гарпия');
INSERT INTO noun (string) VALUES ('hedge-pig');
INSERT INTO noun (string) VALUES ('рог-зверь');
INSERT INTO noun (string) VALUES ('hugger-mugger');
INSERT INTO noun (string) VALUES ('joithead');
INSERT INTO noun (string) VALUES ('lewdster');
INSERT INTO noun (string) VALUES ('lout');
INSERT INTO noun (string) VALUES ('Пирог личинки');
INSERT INTO noun (string) VALUES ('солод-червь');
INSERT INTO noun (string) VALUES ('mammet');
INSERT INTO noun (string) VALUES ('корь');
INSERT INTO noun (string) VALUES ('minnow');
INSERT INTO noun (string) VALUES ('негодяй');
INSERT INTO noun (string) VALUES ('плесень');
INSERT INTO noun (string) VALUES ('mumble-news');
INSERT INTO noun (string) VALUES ('гайка-крюк');
INSERT INTO noun (string) VALUES ('голубиное яйцо');
INSERT INTO noun (string) VALUES ('pignut');
INSERT INTO noun (string) VALUES ('puttock');
INSERT INTO noun (string) VALUES ('pumpion');
INSERT INTO noun (string) VALUES ('ratsbane');
INSERT INTO noun (string) VALUES ('scut');
INSERT INTO noun (string) VALUES ('skainsmate');
INSERT INTO noun (string) VALUES ('струнный');
INSERT INTO noun (string) VALUES ('varlot');
INSERT INTO noun (string) VALUES ('вассал');
INSERT INTO noun (string) VALUES ('сыворотка лица');
INSERT INTO noun (string) VALUES ('трясогузка');


COMMIT;